canonical_name: "nexphone_ch"
version: 70000000002
apns {
  apn {
    name: "NX"
    value: "chili"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "ims"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "enabledMMS"
    bool_value: false
  }
}
last_updated {
  seconds: 1731496787
}
