canonical_name: "alcom_fi"
version: 70000000002
apns {
  apn {
    name: "Internet"
    value: "internet"
    type: DEFAULT
    authtype: 0
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    user_visible: false
  }
  apn {
    name: "mms"
    value: "mms"
    type: MMS
    authtype: 1
    mmsc: "http://mms.amt.aland.fi"
    mmsc_proxy: "194.110.177.70"
    mmsc_proxy_port: "8080"
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
}
last_updated {
  seconds: 1737534997
}
