canonical_name: "epic_mt"
version: 70000000001
apns {
  apn {
    name: "Internet"
    value: "internet"
    type: DEFAULT
    type: SUPL
    authtype: 0
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
}
configs {
}
last_updated {
  seconds: 1729679646
}
