includes:
  - file-removal.yml
  - overlay-inclusion.yml
  - overlay-removal.yml
  - removal.yml

device:
  vendor: google_devices
  system_fs_type: ext4
  kernel_repo_url: https://android.googlesource.com/kernel/common
  has_cellular: true
  build_id: BP2A.250605.031.A2

platform:
  sepolicy_dirs:
    - hardware/google/pixel-sepolicy

filters:
  deprivileged_apks:
    prefix:
      - system_ext/priv-app/PixelNfc/

patches:
  text_files:
    - path: vendor/etc/gnss/gps.xml
      apply:
        - use TLSv1.2-only for SUPL
